# -*- coding: utf-8 -*-
"""Dual-Axis Fragility in Algorithmic Hiring_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hb6zsyM45rcnWj-XV0hlgIfHuNe1kor3
"""

# ============================================================
# Dual-Axis Fragility in Algorithmic Hiring
# Data Wrangling, Descriptive Statistics, and Early Applied Analysis
# Author: Elizabeth B. Taylor
# Institution: Utica University

#1 Install packages not pre-installed
!pip install -q fairlearn pyarrow

#2 Clone the FairCVtest repository and pull the LFS-tracked data file

import subprocess, os

REPO_DIR = "FairCVtest"
USE_REAL_DATA = False

try:
    if not os.path.exists(REPO_DIR):
        env = os.environ.copy()
        env["GIT_LFS_SKIP_SMUDGE"] = "1"  # clone repo structure first, without pulling LFS content
        subprocess.run(["git", "clone", "--depth", "1", "https://github.com/BiDAlab/FairCVtest.git"],
                        check=True, env=env, capture_output=True, text=True, timeout=60)

    # Now pull the actual LFS-tracked data file
    subprocess.run(["git", "lfs", "install"], cwd=REPO_DIR, capture_output=True, text=True)
    lfs_result = subprocess.run(["git", "lfs", "pull"], cwd=REPO_DIR, capture_output=True, text=True, timeout=120)
    print(lfs_result.stdout[-500:], lfs_result.stderr[-500:])

    # A successful pull produces a file >10MB; anything smaller is still just the LFS pointer
    DATA_PATH = os.path.join(REPO_DIR, "data", "FairCVdb.npy")
    USE_REAL_DATA = os.path.exists(DATA_PATH) and os.path.getsize(DATA_PATH) > 10_000_000
except Exception as e:
    print(f"Download step failed ({e}); will use the structurally faithful stand-in generator instead.")

print("Using authentic FairCVdb:", USE_REAL_DATA)
RUN_NAMES = {
    "run1": "Biased Diagnostic Model",
    "run2": "Unbiased Baseline Model",
    "run3": "Mitigated Model (Reweighed)"
}

#3 Load the authentic FairCVdb data into structured DataFrames
import numpy as np
import pandas as pd

if USE_REAL_DATA:
    fairCV = np.load(DATA_PATH, allow_pickle=True).item()
    profile_train = fairCV["Profiles Train"]
    profile_test = fairCV["Profiles Test"]
    blind_train = fairCV["Blind Labels Train"]
    blind_test = fairCV["Blind Labels Test"]
    biased_g_train = fairCV["Biased Labels Train (Gender)"]
    biased_g_test = fairCV["Biased Labels Test (Gender)"]
    biased_e_train = fairCV["Biased Labels Train (Ethnicity)"]
    biased_e_test = fairCV["Biased Labels Test (Ethnicity)"]

    #column names for the first 11 structered (non-embedding) fields, per
    #documented FairCVdb Schema
    cols = ["ethnicity","gender","occupation","suitability","educ_attainment",
                "prev_experience","recommendation","availability","lang_1","lang_2","lang_3"]

    def to_df(profiles, blind, bg, be):
        # profiles[:, 0:11] = structured fields only; columns 11:31 and 31:51 are the
        # two 20-dim face embeddings, not used in this project's core scope
        d = pd.DataFrame(profiles[:, 0:11], columns=cols)
        d["blind_label"] = blind
        d["biased_label_gender"] = bg
        d["biased_label_ethnicity"] = be
        return d

    df_train = to_df(profile_train, blind_train, biased_g_train, biased_e_train)
    df_test  = to_df(profile_test,  blind_test,  biased_g_test,  biased_e_test)
    df = pd.concat([df_train, df_test], ignore_index=True)
    print("Loaded authentic FairCVdb:", df.shape)
else:
    print("Authentic data not available in this environment -- generating structurally faithful stand-in.")

# 4 confirm data is loaded and no missing values
print ('rows, columns:"', df.shape)
print (df.isnull().sum())
print ("total missing cells:", df.isnull().sum().sum())
df.head()

#5 encode occupation fields
df_encoded = pd.get_dummies(df, columns=['occupation'], prefix="occ")
print ("columns after encoding:", df_encoded.head(1))

# 6 Derive the binary hire/reject label
cutoff = df_encoded ["biased_label_gender"].quantile (0.70)
df_encoded ["hire_decision"] =(df_encoded ["biased_label_gender"]>=cutoff)
print (f"cutoff: {cutoff:.4f}")
print ("hire rate by gender:\n", df_encoded.groupby('gender')['hire_decision'].mean())
print ("hire rate by ethnicity:\n", df_encoded.groupby('ethnicity')['hire_decision'].mean())

# 6b. Stratified train/validation split by gender & ethnicity
from sklearn.model_selection import train_test_split

df_encoded["hire_decision"] = df_encoded["hire_decision"].astype(int)  # cast bool -> int
df_encoded["strata"] = df_encoded["gender"].astype(str) + "_" + df_encoded["ethnicity"].astype(str)

train_df, val_df = train_test_split(
    df_encoded, test_size=0.20, stratify=df_encoded["strata"], random_state=42
)
print(f"Train: {train_df.shape[0]} | Validation: {val_df.shape[0]}")
print("Gender balance check (train vs val):")
print(train_df["gender"].value_counts(normalize=True).round(4))
print(val_df["gender"].value_counts(normalize=True).round(4))

"""Axis 2"""

# 7 Axis 2 setup - isolate rejects, mutable vs. immutable features

MUTABLE_FEATURES = ["prev_experience", "lang_1", "lang_2", "lang_3", "availability", "recommendation"]
IMMUTABLE_FEATURES = ["gender", "ethnicity"]
print("Mutable:", MUTABLE_FEATURES)
print("Immutable (protected):", IMMUTABLE_FEATURES)

# 8 descriptive statics
desc_cols = ["educ_attainment","prev_experience","availability","recommendation",
             "suitability","blind_label","biased_label_gender","biased_label_ethnicity"]
df[desc_cols].describe().round(3)

#9 Feature Importance Plotter
import matplotlib.pyplot as plt
import pandas as pd

def plot_importance(model, run_id, filename):
    importances = pd.Series(model.feature_importances_, index=feature_cols).sort_values()

    importances.index = [i.replace('_', ' ').title() for i in importances.index]

    fig, ax = plt.subplots(figsize=(8, 5))
    colors = ["#C9973A" if "Gender" in i else "#1F3A5F" for i in importances.index]

    # Extract top 8 features
    top_features = importances.tail(8)
    top_features.plot(kind='barh', color=colors, ax=ax)

    ax.set_title(f"Feature Importances: {RUN_NAMES[run_id]}", fontweight='bold')
    ax.set_xlabel("Gini Importance")

    # FIX: Expanded right-side padding multiplier from 1.15 to 1.25 to prevent text label clipping
    ax.set_xlim(0, top_features.max() * 1.25)

    for i, v in enumerate(top_features):
        ax.text(v + 0.003, i, f"{v:.3f}", va='center', fontweight='bold', fontsize=9)

    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    plt.show()

#10 Forest baseline - Train a baseline random forest on the gender-biased label deliberately, as a validation
# step: if the audit pipeline can't detect a bias signal that's known to be there by
# construction, it can't be trusted on the unbiased baseline or real mitigation testing later

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score
from fairlearn.metrics import MetricFrame, selection_rate, demographic_parity_ratio


feature_cols = [c for c in train_df.columns if c not in
                ["blind_label","biased_label_gender","biased_label_ethnicity","hire_decision","strata"]]
X_train, y_train = train_df[feature_cols], train_df["hire_decision"]
X_val, y_val = val_df[feature_cols], val_df["hire_decision"]

# n_estimators=200 provides model stability and reduces variance on synthetic data.
# max_depth=8 is deep enough to capture complex bias signals (like gender/ethnicity)
# without overfitting to the synthetic noise in FairCVdb.

clf = RandomForestClassifier(n_estimators=200, max_depth=8, random_state=42, n_jobs=-1)
clf.fit(X_train, y_train)

pred = clf.predict(X_val)
proba = clf.predict_proba(X_val)[:, 1]
rejected = val_df[pred == 0]
print(f"Rejected candidates available for Axis 2 perturbation (by model prediction): {rejected.shape[0]}")

print("Validation accuracy:", round(accuracy_score(y_val, pred), 4))
print("Validation ROC-AUC:", round(roc_auc_score(y_val, proba), 4))

"""AXIS 1 (STRUCTURAL EXCLUSION): FAIRNESS METRICS"""

# 11 Compute selection rate by group and the demographic parity ratio, benchmarked
# against the EEOC's four-fifths (0.80) rule
mf = MetricFrame(metrics=selection_rate, y_true=y_val, y_pred=pred, sensitive_features=val_df["gender"])
print("Selection rate by gender:\n", mf.by_group.round(4))

dpr = demographic_parity_ratio(y_true=y_val, y_pred=pred, sensitive_features=val_df["gender"])
print("\nDemographic Parity Ratio (gender):", round(dpr, 4), "  [EEOC four-fifths threshold = 0.80]")

mf_eth = MetricFrame(metrics=selection_rate, y_true=y_val, y_pred=pred, sensitive_features=val_df["ethnicity"])
print("\nSelection rate by ethnicity:\n", mf_eth.by_group.round(4))

#11b Figure 1: Selection rate by gender (vs. EEOC four-fifths threshold) and by ethnicity
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))

gender_labels = {0.0: "Male", 1.0: "Female"}
ethnicity_labels = {
    0.0: "East Asian",
    1.0: "Sub-Saharan and South Indian",
    2.0: "Caucasian"
}

df_gender_mean = df.groupby("gender")[["blind_label","biased_label_gender"]].mean()
df_gender_mean.index = df_gender_mean.index.map(gender_labels)
df_gender_mean.plot(kind="bar", ax=axes[0], rot=0)
axes[0].set_title("Mean Score by Gender: Blind vs. Biased Label")

df_ethnicity_mean = df.groupby("ethnicity")[["blind_label","biased_label_ethnicity"]].mean()
df_ethnicity_mean.index = df_ethnicity_mean.index.map(ethnicity_labels)
df_ethnicity_mean.plot(kind="bar", ax=axes[1], rot=0)
axes[1].set_title("Mean Score by Ethnicity: Blind vs. Biased Label")
plt.tight_layout()
plt.show()

#12 A fair model shouldn't rank a protected attribute among its most influential features;
# checking this is a secondary, qualitative diagnostic alongside the demographic parity ratio
plot_importance(clf, "run1", "importance_diagnostic.png")

"""AXIS 2 (ADVERSARIAL EXPLOITABILITY): PERTURBATION SEARCH, RUN 1"""

import numpy as np
import pandas as pd

FEATURE_STEPS = {
    "prev_experience": [0, 0.2, 0.4, 0.6, 0.8, 1.0],
    "lang_1": [0, 0.2, 0.4, 0.6, 0.8, 1.0],
    "lang_2": [0, 0.2, 0.4, 0.6, 0.8, 1.0],
    "lang_3": [0, 0.2, 0.4, 0.6, 0.8, 1.0],
    "availability": [0.2, 0.4, 0.6, 0.8, 1.0],
    "recommendation": [0, 1]
}

best_steps_per_feature = pd.DataFrame(index=rejected.index, columns=FEATURE_STEPS.keys(), dtype=float)

for feat, steps in FEATURE_STEPS.items():
    remaining = rejected.copy()
    for n_steps in range(1, len(steps)):
        if remaining.empty:
            break
        current_idx = remaining[feat].apply(lambda v: steps.index(v) if v in steps else None)
        movable = remaining[current_idx.notna() & (current_idx + n_steps < len(steps))]
        if movable.empty:
            continue

        trial_batch = movable[feature_cols].copy()
        new_vals = [steps[steps.index(v) + n_steps] for v in movable[feat]]
        trial_batch[feat] = new_vals

        preds = clf.predict(trial_batch)
        flipped_idx = movable.index[preds == 1]

        best_steps_per_feature.loc[flipped_idx, feat] = n_steps
        remaining = remaining.drop(index=flipped_idx)

valid_flips_mask = best_steps_per_feature.notna().any(axis=1)

flip_df = pd.DataFrame(index=rejected.index)
flip_df["flip_steps"] = best_steps_per_feature.min(axis=1)
# Initialize 'flip_feature' as an object dtype Series to prevent type conflicts
flip_df["flip_feature"] = pd.Series(index=rejected.index, dtype='object')
flip_df.loc[valid_flips_mask, "flip_feature"] = best_steps_per_feature.loc[valid_flips_mask].idxmin(axis=1)

flippable = flip_df["flip_steps"].notna()

print(f"Rejected candidates evaluated: {len(flip_df)}")
print(f"Flippable via a single mutable feature: {flippable.sum()} ({flippable.mean():.1%})")
print("\nDistribution of flip thresholds (steps needed), among flippable candidates:")
print(flip_df.loc[flippable, "flip_steps"].value_counts().sort_index())
print("\nWhich feature most often produced the flip:")
print(flip_df.loc[flippable, "flip_feature"].value_counts())

# Cell 14: Train on the blind (unbiased) label to establish a true fairness baseline
y_train_blind = train_df["blind_label"].apply(lambda v: int(v >= train_df["blind_label"].quantile(0.70)))
y_val_blind = val_df["blind_label"].apply(lambda v: int(v >= train_df["blind_label"].quantile(0.70)))

clf_blind = RandomForestClassifier(n_estimators=200, max_depth=8, random_state=42, n_jobs=-1)
clf_blind.fit(X_train, y_train_blind)
pred_blind = clf_blind.predict(X_val)

print("Run 2 validation accuracy:", round(accuracy_score(y_val_blind, pred_blind), 4))

mf_blind = MetricFrame(metrics=selection_rate, y_true=y_val_blind, y_pred=pred_blind, sensitive_features=val_df["gender"])
print("Run 2 selection rate by gender:\n", mf_blind.by_group.round(4))

dpr_blind = demographic_parity_ratio(y_true=y_val_blind, y_pred=pred_blind, sensitive_features=val_df["gender"])
print("Run 2 Demographic Parity Ratio:", round(dpr_blind, 4))

# Train the baseline model on clean labels
clf_blind = RandomForestClassifier(n_estimators=200, max_depth=8, random_state=42, n_jobs=-1)
clf_blind.fit(X_train, y_train_blind)

# Generate the Feature Importance Assessment for the Baseline
# This proves that when the labels are fair, Gender does not rank in the top features.
plot_importance(clf_blind, "run2", "importance_baseline.png")

# Cell 15: Adversarial Exploitability & Gaming Check (Run 1)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

BUDGET = 2
n_rejected = len(rejected)
n_flipped = (flip_df["flip_steps"] <= BUDGET).sum()
fragility_index = n_flipped / n_rejected

print("--- Axis 2: Adversarial Exploitability Results ---")
print(f"Model Fragility Index (budget {BUDGET} steps): {fragility_index:.1%} (n={n_flipped} out of {n_rejected})")

np.random.seed(42)
random_flips = 0
for idx, row in rejected.iterrows():
    trial = row[feature_cols].copy()
    feat = np.random.choice(list(FEATURE_STEPS.keys()))
    trial[feat] = np.random.choice(FEATURE_STEPS[feat])
    pred = clf.predict(pd.DataFrame([trial]))[0]
    if pred == 1:
        random_flips += 1

random_flip_rate = random_flips / n_rejected
print(f"Random single-feature perturbation flip rate: {random_flip_rate:.1%} (n={random_flips})")
print(f"Targeted search vs. random baseline: {fragility_index:.1%} vs. {random_flip_rate:.1%}")
print("-" * 50)

# Ground-Truth Gaming vs. Improvement Evaluation
flippable_only = flip_df[flip_df["flip_steps"].notna()].copy()
perturbed_rows = []

for idx, row in flippable_only.iterrows():
    feat, n_steps = row["flip_feature"], int(row["flip_steps"])
    steps = FEATURE_STEPS[feat]
    orig_val = rejected.loc[idx, feat]
    if orig_val not in steps:
        continue
    new_val = steps[min(steps.index(orig_val) + n_steps, len(steps) - 1)]
    perturbed_row = rejected.loc[idx, feature_cols].copy()
    perturbed_row[feat] = new_val
    perturbed_rows.append(perturbed_row)

perturbed_df = pd.DataFrame(perturbed_rows, index=flippable_only.index)

# Evaluate perturbed candidates against the unbiased ground-truth baseline
unbiased_preds = clf_blind.predict(perturbed_df[feature_cols])
flip_df.loc[perturbed_df.index, "already_qualified_unbiased"] = (unbiased_preds == 1)

flippable_only = flip_df.loc[perturbed_df.index].copy()
total_flippable = len(flippable_only)

# Positive count calculation
improvement_count = flippable_only["already_qualified_unbiased"].sum()
gaming_count = total_flippable - improvement_count

print(f"--- Gaming vs. Improvement Check (Total Flips: {total_flippable}) ---")
print(f"Gaming (flipped without clearing the unbiased bar, post-edit): {gaming_count} ({gaming_count/total_flippable:.1%})")
print(f"Improvement (the edit itself cleared the unbiased bar, post-edit): {improvement_count} ({improvement_count/total_flippable:.1%})")
print("-" * 50)

crosstab = pd.crosstab(flippable_only["flip_feature"], flippable_only["already_qualified_unbiased"])
crosstab = crosstab.rename(columns={False: "Gaming", True: "Improvement"})
if "Gaming" not in crosstab.columns:
    crosstab["Gaming"] = 0
if "Improvement" not in crosstab.columns:
    crosstab["Improvement"] = 0

crosstab["Gaming Rate"] = crosstab["Gaming"] / (crosstab["Gaming"] + crosstab["Improvement"])
crosstab = crosstab.sort_values("Gaming Rate", ascending=False)
print("Gaming Rate by Feature:")
print(crosstab[["Gaming", "Improvement", "Gaming Rate"]])

# Visualization with expanded right padding
features = pd.Series(clf.feature_importances_, index=feature_cols).sort_values(ascending=True).tail(8)
features.index = [f.replace('_', ' ').title() for f in features.index]
colors = ["#C9973A" if f == "Gender" else "#1F3A5F" for f in features.index]

fig, ax = plt.subplots(figsize=(8.5, 5.0))
ax.barh(features.index, features.values, color=colors)
ax.set_xlim(0, features.max() * 1.25)
ax.set_xlabel("Feature Importance (Gini)")
ax.set_title("Biased Diagnostic: Random Forest Feature Importances")

for i, v in enumerate(features.values):
    ax.text(v + 0.003, i, f"{v:.3f}", va='center', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig("importance_diagnostic.png", dpi=300)
plt.show()

"""RUN 2: BLIND-LABEL FAIRNESS BASELINE"""

# Cell 16: Install AIF360 and apply Reweighing to Run 1's training data
!pip install -q aif360

from aif360.datasets import BinaryLabelDataset
from aif360.algorithms.preprocessing import Reweighing

train_for_aif = train_df[feature_cols + ["hire_decision"]].copy()
bld = BinaryLabelDataset(df=train_for_aif, label_names=["hire_decision"],
                          protected_attribute_names=["gender"],
                          favorable_label=1, unfavorable_label=0)

rw = Reweighing(unprivileged_groups=[{"gender": 1}], privileged_groups=[{"gender": 0}])
bld_reweighted = rw.fit_transform(bld)

clf_mitigated = RandomForestClassifier(n_estimators=200, max_depth=8, random_state=42, n_jobs=-1)
clf_mitigated.fit(X_train, y_train, sample_weight=bld_reweighted.instance_weights)
pred_mitigated = clf_mitigated.predict(X_val)

print("Run 3 (post-mitigation) accuracy:", round(accuracy_score(y_val, pred_mitigated), 4))

mf_mitigated = MetricFrame(metrics=selection_rate, y_true=y_val, y_pred=pred_mitigated, sensitive_features=val_df["gender"])
print("Run 3 selection rate by gender:\n", mf_mitigated.by_group.round(4))

dpr_mitigated = demographic_parity_ratio(y_true=y_val, y_pred=pred_mitigated, sensitive_features=val_df["gender"])
print("Run 3 Demographic Parity Ratio:", round(dpr_mitigated, 4))
print(f"DPR before mitigation: {dpr:.4f}  |  DPR after mitigation: {dpr_mitigated:.4f}")

# Train the mitigated model using sample weights from AIF360
clf_mitigated = RandomForestClassifier(n_estimators=200, max_depth=8, random_state=42, n_jobs=-1)
clf_mitigated.fit(X_train, y_train, sample_weight=bld_reweighted.instance_weights)

# Generate the Feature Importance Assessment for the Mitigated Model
# This visually demonstrates the success of the reweighing technique in reducing
# the model's reliance on protected attributes.
plot_importance(clf_mitigated, "run3", "importance_mitigated.png")

rejected_r3 = val_df[pred_mitigated == 0]
print(f"[Run 3] Rejected candidates available for Axis 2 perturbation (by model prediction): {rejected_r3.shape[0]}")

"""AXIS 2 RE-TEST: PERTURBATION SEARCH AGAINST RUN 3"""

# Cell 17: Axis 2 Flip-Threshold Search Against Run 3 Reweighted Model
import numpy as np
import pandas as pd

best_steps_per_feature_r3 = pd.DataFrame(index=rejected_r3.index, columns=FEATURE_STEPS.keys(), dtype=float)

for feat, steps in FEATURE_STEPS.items():
    remaining = rejected_r3.copy()
    for n_steps in range(1, len(steps)):
        if remaining.empty:
            break
        current_idx = remaining[feat].apply(lambda v: steps.index(v) if v in steps else None)
        movable = remaining[current_idx.notna() & (current_idx + n_steps < len(steps))]
        if movable.empty:
            continue

        trial_batch = movable[feature_cols].copy()
        new_vals = [steps[steps.index(v) + n_steps] for v in movable[feat]]
        trial_batch[feat] = new_vals

        preds = clf_mitigated.predict(trial_batch)
        flipped_idx = movable.index[preds == 1]

        best_steps_per_feature_r3.loc[flipped_idx, feat] = n_steps
        remaining = remaining.drop(index=flipped_idx)


valid_flips_mask_r3 = best_steps_per_feature_r3.notna().any(axis=1)

flip_df_r3 = pd.DataFrame(index=rejected_r3.index)
flip_df_r3["flip_steps"] = best_steps_per_feature_r3.min(axis=1)
flip_df_r3["flip_feature"] = np.nan
flip_df_r3.loc[valid_flips_mask_r3, "flip_feature"] = best_steps_per_feature_r3.loc[valid_flips_mask_r3].idxmin(axis=1)

flippable_r3 = flip_df_r3["flip_steps"].notna()

print(f"[Run 3] Rejected candidates evaluated: {len(flip_df_r3)}")
print(f"[Run 3] Flippable via a single mutable feature: {flippable_r3.sum()} ({flippable_r3.mean():.1%})")
print("\n[Run 3] Distribution of flip thresholds, among flippable candidates:")
print(flip_df_r3.loc[flippable_r3, "flip_steps"].value_counts().sort_index())
print("\n[Run 3] Which feature most often produced the flip:")
print(flip_df_r3.loc[flippable_r3, "flip_feature"].value_counts())

# Cell 18: Model Fragility Index for Run 3 + random baseline
fragility_index_r3 = (flip_df_r3["flip_steps"] <= BUDGET).mean()
print(f"[Run 3] Model Fragility Index (budget = {BUDGET} steps): {fragility_index_r3:.1%}")

np.random.seed(42)
random_flips_r3 = 0
for _, row in rejected_r3.iterrows():
    trial = row[feature_cols].copy()
    feat = np.random.choice(list(FEATURE_STEPS.keys()))
    trial[feat] = np.random.choice(FEATURE_STEPS[feat])
    pred = clf_mitigated.predict(pd.DataFrame([trial]))[0]
    if pred == 1:
        random_flips_r3 += 1

random_flip_rate_r3 = random_flips_r3 / len(rejected_r3)
print(f"[Run 3] Random single-feature perturbation flip rate: {random_flip_rate_r3:.1%}")
print(f"[Run 3] Targeted search vs. random baseline: {fragility_index_r3:.1%} vs. {random_flip_rate_r3:.1%}")

# Cell 19: Ground-Truth Check for Run 3 Flips (Gaming vs. Improvement)
import pandas as pd

flippable_only_r3 = flip_df_r3[flip_df_r3["flip_steps"].notna()].copy()
perturbed_rows = []

for idx, row in flippable_only_r3.iterrows():
    feat, n_steps = row["flip_feature"], int(row["flip_steps"])
    steps = FEATURE_STEPS[feat]
    orig_val = rejected_r3.loc[idx, feat]
    if orig_val not in steps:
        continue
    new_val = steps[min(steps.index(orig_val) + n_steps, len(steps) - 1)]
    perturbed_row = rejected_r3.loc[idx, feature_cols].copy()
    perturbed_row[feat] = new_val
    perturbed_rows.append(perturbed_row)

perturbed_df_r3 = pd.DataFrame(perturbed_rows, index=flippable_only_r3.index)

# Evaluate Run 3 perturbed candidates against unbiased baseline
unbiased_preds_r3 = clf_blind.predict(perturbed_df_r3[feature_cols])
flip_df_r3.loc[perturbed_df_r3.index, "already_qualified_unbiased"] = (unbiased_preds_r3 == 1)

flippable_only_r3 = flip_df_r3.loc[perturbed_df_r3.index].copy()
total_r3 = len(flippable_only_r3)

# FIX: Positive count calculation
improvement_count_r3 = flippable_only_r3["already_qualified_unbiased"].sum()
gaming_count_r3 = total_r3 - improvement_count_r3

print(f"[Run 3] Gaming (flipped without clearing the unbiased bar, post-edit): {gaming_count_r3} ({gaming_count_r3/total_r3:.1%})")
print(f"[Run 3] Improvement / bias-correction (post-edit): {improvement_count_r3} ({improvement_count_r3/total_r3:.1%})")

crosstab_r3 = pd.crosstab(flippable_only_r3["flip_feature"], flippable_only_r3["already_qualified_unbiased"])
crosstab_r3 = crosstab_r3.rename(columns={False: "Gaming", True: "Improvement"})
if "Gaming" not in crosstab_r3.columns:
    crosstab_r3["Gaming"] = 0
if "Improvement" not in crosstab_r3.columns:
    crosstab_r3["Improvement"] = 0

crosstab_r3["gaming_rate"] = (crosstab_r3["Gaming"] / (crosstab_r3["Gaming"] + crosstab_r3["Improvement"])).round(3)
crosstab_r3 = crosstab_r3.sort_values("gaming_rate", ascending=False)
print(crosstab_r3)

# Cell 20: Side-by-side fragility comparison, Run 1 vs. Run 3
print("FINAL RESEARCH SUMMARY: SIDE-BY-SIDE FRAGILITY")
print(f"{RUN_NAMES['run1']}: MFI = {fragility_index:.1%} (Random Baseline: {random_flip_rate:.1%})")
print(f"{RUN_NAMES['run3']}: MFI = {fragility_index_r3:.1%} (Random Baseline: {random_flip_rate_r3:.1%})")
print("-" * 50)
print(f"Observation: Fragility increased by {fragility_index_r3 - fragility_index:.1%} after bias mitigation.")

# Cell 21: Dual-Axis Risk Quadrant — Run 1 and Run 3 plotted against the Risk Tier Criteria
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import ListedColormap

RED_TIER, GOLD_TIER, GREEN_TIER = "#B0342D", "#C9973A", "#2E8B57"

x = np.linspace(0, 1, 400)
y = np.linspace(0, 100, 400)
X, Y = np.meshgrid(x, y)

# Risk tier resolution: High checked first, then Low, else Moderate —
# the stated OR/AND criteria are not mutually exclusive on their own.
high = (X < 0.70) | (Y > 60)
low = (~high) & (X >= 0.80) & (Y < 30)
moderate = (~high) & (~low)

Z = np.zeros_like(X)
Z[moderate] = 1
Z[low] = 2
Z[high] = 0

fig, ax = plt.subplots(figsize=(8, 6.2))
ax.pcolormesh(X, Y, Z, cmap=ListedColormap([RED_TIER, GOLD_TIER, GREEN_TIER]), shading='auto', alpha=0.35, zorder=0)

ax.axvline(0.70, color="#1F3A5F", linestyle=":", linewidth=1.2)
ax.axvline(0.80, color="#1F3A5F", linestyle="--", linewidth=1.4)
ax.axhline(60, color="#1F3A5F", linestyle="--", linewidth=1.4)
ax.axhline(30, color="#1F3A5F", linestyle=":", linewidth=1.2)

# Run 1 and Run 3, pulled directly from this notebook's own computed values
ax.scatter([dpr], [fragility_index * 100], s=170, color=RED_TIER, edgecolor='black',
           linewidth=1.3, zorder=5, marker='o')
ax.annotate(RUN_NAMES['run1'], (dpr, fragility_index * 100), textcoords="offset points",
            xytext=(8, 10), fontsize=11, fontweight='bold')

ax.scatter([dpr_mitigated], [fragility_index_r3 * 100], s=170, color=RED_TIER, edgecolor='black',
           linewidth=1.3, zorder=5, marker='s')
ax.annotate(RUN_NAMES['run3'], (dpr_mitigated, fragility_index_r3 * 100), textcoords="offset points",
            xytext=(10, -6), fontsize=11, fontweight='bold')

ax.set_xlim(0, 1); ax.set_ylim(0, 100)
ax.set_xlabel("Demographic Parity Ratio (Axis 1)", fontsize=12, fontweight='bold')
ax.set_ylabel("Model Fragility Index (Axis 2, %)", fontsize=12, fontweight='bold')
ax.set_title("Dual-Axis Risk Classification: Run 1 and Run 3 vs. Risk Tier Criteria", fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig("risk_quadrant.png", dpi=220, bbox_inches='tight', facecolor='white')
plt.show()

# Cell 22: SHAP (SHapley Additive exPlanations) Model Explainability
import shap
import matplotlib.pyplot as plt
import numpy as np

def compute_shap_summary(model, X_data, feature_names, title, filename):
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_data)

    # Handle both older list-per-class and 3D array return shapes from SHAP
    if isinstance(shap_values, list):
        values_for_hire_class = shap_values[1]
    elif getattr(shap_values, 'ndim', 0) == 3:
        values_for_hire_class = shap_values[:, :, 1]
    else:
        values_for_hire_class = shap_values

        cleaned_feature_names = [f.replace('_', ' ').title() for f in feature_names]

    plt.figure(figsize=(10, 6))
    shap.summary_plot(
        values_for_hire_class,
        X_data,
        feature_names=cleaned_feature_names,
        show=False
    )
    plt.title(title, fontweight='bold', fontsize=12, pad=15)
    plt.tight_layout()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    plt.show()

# Compute and render SHAP summary plot for the Run 3 Mitigated Model
compute_shap_summary(
    model=clf_mitigated,
    X_data=X_val,
    feature_names=feature_cols,
    title="SHAP Feature Contribution: Mitigated Model (Run 3)",
    filename="shap_summary_run3.png"
)